kind: pipeline
type: kubernetes
name: develop
steps:
  - name: build-push
    image: docker:dind
    volumes:
      - name: dockersock
        path: /run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      IMAGE: mysql-backup-to-azure
    commands:
      - sleep 5 #
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build . -t $DOCKER_USER/$IMAGE:develop
      - docker push $DOCKER_USER/$IMAGE:develop
volumes:
  - name: dockersock
    host:
      path: /run
---
kind: pipeline
type: kubernetes
name: production

steps:
  - name: build-push
    image: docker:dind
    volumes:
      - name: dockersock
        path: /run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      IMAGE: mysql-backup-to-azure
    commands:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag -t $DOCKER_USER/$IMAGE:$DRONE_COMMIT_SHA $DOCKER_USER/$IMAGE_NAME:latest
    - docker push $DOCKER_USER/$IMAGE_NAME

volumes:
  - name: dockersock
    host:
      path: /run
trigger:
  event:
    - promote
  target:
    - production
