apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup-to-azure
  labels:
    app: mysql-backup
spec:
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup-azure
              image: adamhancock/mysql-backup-to-azure
              env:
                - name: mysql_host
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: host
                - name: mysql_user
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: user
                - name: mysql_password
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: password
                - name: azure_account
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: account
                - name: azure_accountKey
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: accountKey
                - name: azure_container
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: container

          restartPolicy: Never
      backoffLimit: 4
